In [11]:
import torch 
import time
import numpy as np
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [14]:
#percentage percentage time
#time taking to execute the block/

start_time = time.time()
#matrix operations are here

zeros = torch.zeros(1,1)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000


In [9]:
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)  #mutilpy and get the new random tensor:
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


#the first one os GPU and the second  one is CPU
#not a lot to do for the CPU

#now we will change some stuffs inorder to alter to the cpu, simple multiplications to do now:


torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100).to(device)
np_rand1 = torch.rand(100, 100)
np_rand2 = torch.rand(100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)  #mutilpy and get the new random tensor:
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

#the dimensionality does matter:
# when we give task to parallel processing, it will be a lot more faster.
#GPU matters for increasing the efficiency of the training process.






0.02792430
0.19067049
0.04804444
0.00000000


In [19]:
#torch.stack, torch.trail. torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax(show all the examles of the functions and methods with the pytorch docs)


#define a probablity tensor:

probabilities = torch.tensor([0.1, 0.9])

# 10% or 0.1 => 0, 90% or 0.9 => 1, each probablities points to the index of the probablity in the tensor
samples = torch.multinomial(probabilities, num_samples=10, replacement = True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])


In [24]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim =0)
out

tensor([1, 2, 3, 4, 5])

In [26]:
out = torch.tril(torch.ones(5,5))
out   #triangle format top left to bottom right, when u ar trying to predict integers. talking to each other in history.
#making sure we can predict when knowing the answer. know from histroy of knowledge, which one to predict.

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [27]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [28]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [29]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [30]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape


torch.Size([4, 3, 2])

In [32]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])



#stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3,3, bias = False)
print(linear(sample))


tensor([6.6217, 6.1000, 1.0066], grad_fn=<SqueezeBackward4>)


In [33]:
import torch.nn.functional as F

#Create a tensor:
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#Apply softmax using the torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim = 0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])
